#include <KernelExport.h>


//int nv_acpi_ddc_method(void) {panic("[!!!] nv_acpi_ddc_method: not implemented\n"); return -1;}
//int nv_acpi_dod_method(void) {panic("[!!!] nv_acpi_dod_method: not implemented\n"); return -1;}
//int nv_acpi_get_powersource(void) {panic("[!!!] nv_acpi_get_powersource: not implemented\n"); return -1;}
//int nv_acpi_is_battery_present(void) {panic("[!!!] nv_acpi_is_battery_present: not implemented\n"); return -1;}
//int nv_acpi_methods_init(void) {panic("[!!!] nv_acpi_methods_init: not implemented\n"); return -1;}
//int nv_acpi_methods_uninit(void) {panic("[!!!] nv_acpi_methods_uninit: not implemented\n"); return -1;}
//int nv_acpi_mux_method(void) {panic("[!!!] nv_acpi_mux_method: not implemented\n"); return -1;}
//int nv_acpi_rom_method(void) {panic("[!!!] nv_acpi_rom_method: not implemented\n"); return -1;}
//int nv_acquire_fabric_mgmt_cap(void) {panic("[!!!] nv_acquire_fabric_mgmt_cap: not implemented\n"); return -1;}
//int nv_add_mapping_context_to_file(void) {panic("[!!!] nv_add_mapping_context_to_file: not implemented\n"); return -1;}
int nv_alias_pages(void) {panic("[!!!] nv_alias_pages: not implemented\n"); return -1;}
//int nv_alloc_kernel_mapping(void) {panic("[!!!] nv_alloc_kernel_mapping: not implemented\n"); return -1;}
//int nv_alloc_pages(void) {panic("[!!!] nv_alloc_pages: not implemented\n"); return -1;}
//int nv_alloc_user_mapping(void) {panic("[!!!] nv_alloc_user_mapping: not implemented\n"); return -1;}
int nv_control_soc_irqs(void) {panic("[!!!] nv_control_soc_irqs: not implemented\n"); return -1;}
int nv_dma_cache_invalidate(void) {panic("[!!!] nv_dma_cache_invalidate: not implemented\n"); return -1;}
int nv_dma_enable_nvlink(void) {panic("[!!!] nv_dma_enable_nvlink: not implemented\n"); return -1;}
int nv_dma_import_dma_buf(void) {panic("[!!!] nv_dma_import_dma_buf: not implemented\n"); return -1;}
int nv_dma_import_from_fd(void) {panic("[!!!] nv_dma_import_from_fd: not implemented\n"); return -1;}
int nv_dma_import_sgt(void) {panic("[!!!] nv_dma_import_sgt: not implemented\n"); return -1;}
int nv_dma_map_alloc(void) {panic("[!!!] nv_dma_map_alloc: not implemented\n"); return -1;}
int nv_dma_map_mmio(void) {panic("[!!!] nv_dma_map_mmio: not implemented\n"); return -1;}
int nv_dma_map_pages(void) {panic("[!!!] nv_dma_map_pages: not implemented\n"); return -1;}
int nv_dma_map_peer(void) {panic("[!!!] nv_dma_map_peer: not implemented\n"); return -1;}
int nv_dma_release_dma_buf(void) {panic("[!!!] nv_dma_release_dma_buf: not implemented\n"); return -1;}
int nv_dma_release_sgt(void) {panic("[!!!] nv_dma_release_sgt: not implemented\n"); return -1;}
int nv_dma_unmap_alloc(void) {panic("[!!!] nv_dma_unmap_alloc: not implemented\n"); return -1;}
int nv_dma_unmap_mmio(void) {panic("[!!!] nv_dma_unmap_mmio: not implemented\n"); return -1;}
int nv_dma_unmap_pages(void) {panic("[!!!] nv_dma_unmap_pages: not implemented\n"); return -1;}
int nv_dma_unmap_peer(void) {panic("[!!!] nv_dma_unmap_peer: not implemented\n"); return -1;}
int nv_flush_coherent_cpu_cache_range(void) {panic("[!!!] nv_flush_coherent_cpu_cache_range: not implemented\n"); return -1;}
//int nv_free_kernel_mapping(void) {panic("[!!!] nv_free_kernel_mapping: not implemented\n"); return -1;}
//int nv_free_pages(void) {panic("[!!!] nv_free_pages: not implemented\n"); return -1;}
//int nv_free_user_mapping(void) {panic("[!!!] nv_free_user_mapping: not implemented\n"); return -1;}
int nv_get_adapter_state(void) {panic("[!!!] nv_get_adapter_state: not implemented\n"); return -1;}
//int nv_get_ctl_state(void) {panic("[!!!] nv_get_ctl_state: not implemented\n"); return -1;}
//int nv_get_dev_minor(void) {panic("[!!!] nv_get_dev_minor: not implemented\n"); return -1;}
//int nv_get_device_memory_config(void) {panic("[!!!] nv_get_device_memory_config: not implemented\n"); return -1;}
//int nv_get_dma_start_address(void) {panic("[!!!] nv_get_dma_start_address: not implemented\n"); return -1;}
int nv_get_event(void) {panic("[!!!] nv_get_event: not implemented\n"); return -1;}
//int nv_get_file_private(void) {panic("[!!!] nv_get_file_private: not implemented\n"); return -1;}
//int nv_get_firmware(void) {panic("[!!!] nv_get_firmware: not implemented\n"); return -1;}
int nv_get_ibmnpu_genreg_info(void) {panic("[!!!] nv_get_ibmnpu_genreg_info: not implemented\n"); return -1;}
int nv_get_ibmnpu_relaxed_ordering_mode(void) {panic("[!!!] nv_get_ibmnpu_relaxed_ordering_mode: not implemented\n"); return -1;}
int nv_get_num_phys_pages(void) {panic("[!!!] nv_get_num_phys_pages: not implemented\n"); return -1;}
//int nv_get_os_type(void) {panic("[!!!] nv_get_os_type: not implemented\n"); return -1;}
int nv_get_phys_pages(void) {panic("[!!!] nv_get_phys_pages: not implemented\n"); return -1;}
//int nv_get_usermap_access_params(void) {panic("[!!!] nv_get_usermap_access_params: not implemented\n"); return -1;}
//int nv_i2c_add_adapter(void) {panic("[!!!] nv_i2c_add_adapter: not implemented\n"); return -1;}
//int nv_i2c_del_adapter(void) {panic("[!!!] nv_i2c_del_adapter: not implemented\n"); return -1;}
//int nv_is_chassis_notebook(void) {panic("[!!!] nv_is_chassis_notebook: not implemented\n"); return -1;}
//int nv_is_gpu_accessible(void) {panic("[!!!] nv_is_gpu_accessible: not implemented\n"); return -1;}
//int nv_log_error(void) {panic("[!!!] nv_log_error: not implemented\n"); return -1;}
int nv_parms(void) {panic("[!!!] nv_parms: not implemented\n"); return -1;}
int nv_pci_trigger_recovery(void) {panic("[!!!] nv_pci_trigger_recovery: not implemented\n"); return -1;}
//int nv_post_event(void) {panic("[!!!] nv_post_event: not implemented\n"); return -1;}
//int nv_printf(void) {panic("[!!!] nv_printf: not implemented\n"); return -1;}
//int nv_put_file_private(void) {panic("[!!!] nv_put_file_private: not implemented\n"); return -1;}
//int nv_put_firmware(void) {panic("[!!!] nv_put_firmware: not implemented\n"); return -1;}
int nv_register_peer_io_mem(void) {panic("[!!!] nv_register_peer_io_mem: not implemented\n"); return -1;}
int nv_register_phys_pages(void) {panic("[!!!] nv_register_phys_pages: not implemented\n"); return -1;}
int nv_register_sgt(void) {panic("[!!!] nv_register_sgt: not implemented\n"); return -1;}
int nv_register_user_pages(void) {panic("[!!!] nv_register_user_pages: not implemented\n"); return -1;}
//int nv_requires_dma_remap(void) {panic("[!!!] nv_requires_dma_remap: not implemented\n"); return -1;}
//int nv_schedule_uvm_isr(void) {panic("[!!!] nv_schedule_uvm_isr: not implemented\n"); return -1;}
//int nv_set_dma_address_size(void) {panic("[!!!] nv_set_dma_address_size: not implemented\n"); return -1;}
//int nv_start_rc_timer(void) {panic("[!!!] nv_start_rc_timer: not implemented\n"); return -1;}
//int nv_stop_rc_timer(void) {panic("[!!!] nv_stop_rc_timer: not implemented\n"); return -1;}
int nv_unregister_peer_io_mem(void) {panic("[!!!] nv_unregister_peer_io_mem: not implemented\n"); return -1;}
int nv_unregister_phys_pages(void) {panic("[!!!] nv_unregister_phys_pages: not implemented\n"); return -1;}
int nv_unregister_sgt(void) {panic("[!!!] nv_unregister_sgt: not implemented\n"); return -1;}
int nv_unregister_user_pages(void) {panic("[!!!] nv_unregister_user_pages: not implemented\n"); return -1;}
int nv_wait_for_ibmnpu_rsync(void) {panic("[!!!] nv_wait_for_ibmnpu_rsync: not implemented\n"); return -1;}
int nvidia_caps_root(void) {panic("[!!!] nvidia_caps_root: not implemented\n"); return -1;}
int nvlink_acquire_fabric_mgmt_cap(void) {panic("[!!!] nvlink_acquire_fabric_mgmt_cap: not implemented\n"); return -1;}
//int nvlink_assert(void) {panic("[!!!] nvlink_assert: not implemented\n"); return -1;}
//int nvlink_free(void) {panic("[!!!] nvlink_free: not implemented\n"); return -1;}
int nvlink_is_admin(void) {panic("[!!!] nvlink_is_admin: not implemented\n"); return -1;}
int nvlink_is_fabric_manager(void) {panic("[!!!] nvlink_is_fabric_manager: not implemented\n"); return -1;}
//int nvlink_malloc(void) {panic("[!!!] nvlink_malloc: not implemented\n"); return -1;}
//int nvlink_memcpy(void) {panic("[!!!] nvlink_memcpy: not implemented\n"); return -1;}
//int nvlink_memset(void) {panic("[!!!] nvlink_memset: not implemented\n"); return -1;}
//int nvlink_sleep(void) {panic("[!!!] nvlink_sleep: not implemented\n"); return -1;}
//int nvlink_strcmp(void) {panic("[!!!] nvlink_strcmp: not implemented\n"); return -1;}
//int nvlink_strcpy(void) {panic("[!!!] nvlink_strcpy: not implemented\n"); return -1;}
//int nvlink_strlen(void) {panic("[!!!] nvlink_strlen: not implemented\n"); return -1;}
int nvswitch_os_acquire_fabric_mgmt_cap(void) {panic("[!!!] nvswitch_os_acquire_fabric_mgmt_cap: not implemented\n"); return -1;}
int nvswitch_os_add_client_event(void) {panic("[!!!] nvswitch_os_add_client_event: not implemented\n"); return -1;}
int nvswitch_os_alloc_contig_memory(void) {panic("[!!!] nvswitch_os_alloc_contig_memory: not implemented\n"); return -1;}
int nvswitch_os_assert_log(void) {panic("[!!!] nvswitch_os_assert_log: not implemented\n"); return -1;}
int nvswitch_os_free(void) {panic("[!!!] nvswitch_os_free: not implemented\n"); return -1;}
int nvswitch_os_free_contig_memory(void) {panic("[!!!] nvswitch_os_free_contig_memory: not implemented\n"); return -1;}
int nvswitch_os_get_platform_time(void) {panic("[!!!] nvswitch_os_get_platform_time: not implemented\n"); return -1;}
int nvswitch_os_get_supported_register_events_params(void) {panic("[!!!] nvswitch_os_get_supported_register_events_params: not implemented\n"); return -1;}
int nvswitch_os_is_admin(void) {panic("[!!!] nvswitch_os_is_admin: not implemented\n"); return -1;}
int nvswitch_os_is_fabric_manager(void) {panic("[!!!] nvswitch_os_is_fabric_manager: not implemented\n"); return -1;}
int nvswitch_os_is_uuid_in_blacklist(void) {panic("[!!!] nvswitch_os_is_uuid_in_blacklist: not implemented\n"); return -1;}
int nvswitch_os_malloc_trace(void) {panic("[!!!] nvswitch_os_malloc_trace: not implemented\n"); return -1;}
int nvswitch_os_map_dma_region(void) {panic("[!!!] nvswitch_os_map_dma_region: not implemented\n"); return -1;}
int nvswitch_os_mem_read32(void) {panic("[!!!] nvswitch_os_mem_read32: not implemented\n"); return -1;}
int nvswitch_os_mem_write32(void) {panic("[!!!] nvswitch_os_mem_write32: not implemented\n"); return -1;}
int nvswitch_os_memcpy(void) {panic("[!!!] nvswitch_os_memcpy: not implemented\n"); return -1;}
int nvswitch_os_memset(void) {panic("[!!!] nvswitch_os_memset: not implemented\n"); return -1;}
int nvswitch_os_notify_client_event(void) {panic("[!!!] nvswitch_os_notify_client_event: not implemented\n"); return -1;}
int nvswitch_os_override_platform(void) {panic("[!!!] nvswitch_os_override_platform: not implemented\n"); return -1;}
int nvswitch_os_print(void) {panic("[!!!] nvswitch_os_print: not implemented\n"); return -1;}
int nvswitch_os_read_registry_dword(void) {panic("[!!!] nvswitch_os_read_registry_dword: not implemented\n"); return -1;}
int nvswitch_os_remove_client_event(void) {panic("[!!!] nvswitch_os_remove_client_event: not implemented\n"); return -1;}
int nvswitch_os_set_dma_mask(void) {panic("[!!!] nvswitch_os_set_dma_mask: not implemented\n"); return -1;}
int nvswitch_os_sleep(void) {panic("[!!!] nvswitch_os_sleep: not implemented\n"); return -1;}
int nvswitch_os_snprintf(void) {panic("[!!!] nvswitch_os_snprintf: not implemented\n"); return -1;}
int nvswitch_os_strlen(void) {panic("[!!!] nvswitch_os_strlen: not implemented\n"); return -1;}
int nvswitch_os_strncmp(void) {panic("[!!!] nvswitch_os_strncmp: not implemented\n"); return -1;}
int nvswitch_os_strncpy(void) {panic("[!!!] nvswitch_os_strncpy: not implemented\n"); return -1;}
int nvswitch_os_sync_dma_region_for_cpu(void) {panic("[!!!] nvswitch_os_sync_dma_region_for_cpu: not implemented\n"); return -1;}
int nvswitch_os_sync_dma_region_for_device(void) {panic("[!!!] nvswitch_os_sync_dma_region_for_device: not implemented\n"); return -1;}
int nvswitch_os_unmap_dma_region(void) {panic("[!!!] nvswitch_os_unmap_dma_region: not implemented\n"); return -1;}
int nvswitch_os_vsnprintf(void) {panic("[!!!] nvswitch_os_vsnprintf: not implemented\n"); return -1;}
//int os_acquire_mutex(void) {panic("[!!!] os_acquire_mutex: not implemented\n"); return -1;}
//int os_acquire_semaphore(void) {panic("[!!!] os_acquire_semaphore: not implemented\n"); return -1;}
//int os_acquire_spinlock(void) {panic("[!!!] os_acquire_spinlock: not implemented\n"); return -1;}
//int os_add_record_for_crashLog(void) {panic("[!!!] os_add_record_for_crashLog: not implemented\n"); return -1;}
//int os_alloc_mem(void) {panic("[!!!] os_alloc_mem: not implemented\n"); return -1;}
//int os_alloc_mutex(void) {panic("[!!!] os_alloc_mutex: not implemented\n"); return -1;}
int os_alloc_pages_node(void) {panic("[!!!] os_alloc_pages_node: not implemented\n"); return -1;}
//int os_alloc_semaphore(void) {panic("[!!!] os_alloc_semaphore: not implemented\n"); return -1;}
//int os_alloc_spinlock(void) {panic("[!!!] os_alloc_spinlock: not implemented\n"); return -1;}
//int os_alloc_wait_queue(void) {panic("[!!!] os_alloc_wait_queue: not implemented\n"); return -1;}
//int os_allow_priority_override(void) {panic("[!!!] os_allow_priority_override: not implemented\n"); return -1;}
//int os_bug_check(void) {panic("[!!!] os_bug_check: not implemented\n"); return -1;}
int os_close_file(void) {panic("[!!!] os_close_file: not implemented\n"); return -1;}
//int os_cond_acquire_mutex(void) {panic("[!!!] os_cond_acquire_mutex: not implemented\n"); return -1;}
//int os_cond_acquire_semaphore(void) {panic("[!!!] os_cond_acquire_semaphore: not implemented\n"); return -1;}
int os_count_tail_pages(void) {panic("[!!!] os_count_tail_pages: not implemented\n"); return -1;}
//int os_dbg_breakpoint(void) {panic("[!!!] os_dbg_breakpoint: not implemented\n"); return -1;}
//int os_dbg_init(void) {panic("[!!!] os_dbg_init: not implemented\n"); return -1;}
int os_dbg_set_level(void) {panic("[!!!] os_dbg_set_level: not implemented\n"); return -1;}
//int os_delay(void) {panic("[!!!] os_delay: not implemented\n"); return -1;}
//int os_delay_us(void) {panic("[!!!] os_delay_us: not implemented\n"); return -1;}
//int os_delete_record_for_crashLog(void) {panic("[!!!] os_delete_record_for_crashLog: not implemented\n"); return -1;}
//int os_disable_console_access(void) {panic("[!!!] os_disable_console_access: not implemented\n"); return -1;}
int os_dma_buf_enabled(void) {panic("[!!!] os_dma_buf_enabled: not implemented\n"); return -1;}
int os_dump_stack(void) {panic("[!!!] os_dump_stack: not implemented\n"); return -1;}
//int os_enable_console_access(void) {panic("[!!!] os_enable_console_access: not implemented\n"); return -1;}
//int os_flush_cpu_cache_all(void) {panic("[!!!] os_flush_cpu_cache_all: not implemented\n"); return -1;}
//int os_flush_cpu_write_combine_buffer(void) {panic("[!!!] os_flush_cpu_write_combine_buffer: not implemented\n"); return -1;}
int os_flush_user_cache(void) {panic("[!!!] os_flush_user_cache: not implemented\n"); return -1;}
int os_flush_work_queue(void) {panic("[!!!] os_flush_work_queue: not implemented\n"); return -1;}
//int os_free_mem(void) {panic("[!!!] os_free_mem: not implemented\n"); return -1;}
//int os_free_mutex(void) {panic("[!!!] os_free_mutex: not implemented\n"); return -1;}
//int os_free_semaphore(void) {panic("[!!!] os_free_semaphore: not implemented\n"); return -1;}
//int os_free_spinlock(void) {panic("[!!!] os_free_spinlock: not implemented\n"); return -1;}
//int os_free_wait_queue(void) {panic("[!!!] os_free_wait_queue: not implemented\n"); return -1;}
//int os_get_acpi_rsdp_from_uefi(void) {panic("[!!!] os_get_acpi_rsdp_from_uefi: not implemented\n"); return -1;}
//int os_get_cpu_count(void) {panic("[!!!] os_get_cpu_count: not implemented\n"); return -1;}
//int os_get_cpu_frequency(void) {panic("[!!!] os_get_cpu_frequency: not implemented\n"); return -1;}
//int os_get_cpu_number(void) {panic("[!!!] os_get_cpu_number: not implemented\n"); return -1;}
//int os_get_current_process(void) {panic("[!!!] os_get_current_process: not implemented\n"); return -1;}
//int os_get_current_process_name(void) {panic("[!!!] os_get_current_process_name: not implemented\n"); return -1;}
//int os_get_current_thread(void) {panic("[!!!] os_get_current_thread: not implemented\n"); return -1;}
//int os_get_current_tick(void) {panic("[!!!] os_get_current_tick: not implemented\n"); return -1;}
//int os_get_current_tick_hr(void) {panic("[!!!] os_get_current_tick_hr: not implemented\n"); return -1;}
//int os_get_current_time(void) {panic("[!!!] os_get_current_time: not implemented\n"); return -1;}
//int os_get_euid(void) {panic("[!!!] os_get_euid: not implemented\n"); return -1;}
//int os_get_num_phys_pages(void) {panic("[!!!] os_get_num_phys_pages: not implemented\n"); return -1;}
int os_get_page(void) {panic("[!!!] os_get_page: not implemented\n"); return -1;}
int os_get_page_refcount(void) {panic("[!!!] os_get_page_refcount: not implemented\n"); return -1;}
int os_get_random_bytes(void) {panic("[!!!] os_get_random_bytes: not implemented\n"); return -1;}
//int os_get_screen_info(void) {panic("[!!!] os_get_screen_info: not implemented\n"); return -1;}
int os_get_smbios_header(void) {panic("[!!!] os_get_smbios_header: not implemented\n"); return -1;}
//int os_get_tick_resolution(void) {panic("[!!!] os_get_tick_resolution: not implemented\n"); return -1;}
int os_get_version_info(void) {panic("[!!!] os_get_version_info: not implemented\n"); return -1;}
int os_io_read_byte(void) {panic("[!!!] os_io_read_byte: not implemented\n"); return -1;}
int os_io_read_word(void) {panic("[!!!] os_io_read_word: not implemented\n"); return -1;}
int os_io_write_byte(void) {panic("[!!!] os_io_write_byte: not implemented\n"); return -1;}
int os_io_write_word(void) {panic("[!!!] os_io_write_word: not implemented\n"); return -1;}
//int os_is_administrator(void) {panic("[!!!] os_is_administrator: not implemented\n"); return -1;}
//int os_is_efi_enabled(void) {panic("[!!!] os_is_efi_enabled: not implemented\n"); return -1;}
//int os_is_isr(void) {panic("[!!!] os_is_isr: not implemented\n"); return -1;}
//int os_is_nvswitch_present(void) {panic("[!!!] os_is_nvswitch_present: not implemented\n"); return -1;}
//int os_is_vgx_hyper(void) {panic("[!!!] os_is_vgx_hyper: not implemented\n"); return -1;}
int os_lock_user_pages(void) {panic("[!!!] os_lock_user_pages: not implemented\n"); return -1;}
int os_lookup_user_io_memory(void) {panic("[!!!] os_lookup_user_io_memory: not implemented\n"); return -1;}
//int os_map_kernel_space(void) {panic("[!!!] os_map_kernel_space: not implemented\n"); return -1;}
//int os_map_user_space(void) {panic("[!!!] os_map_user_space: not implemented\n"); return -1;}
//int os_match_mmap_offset(void) {panic("[!!!] os_match_mmap_offset: not implemented\n"); return -1;}
//int os_mem_cmp(void) {panic("[!!!] os_mem_cmp: not implemented\n"); return -1;}
//int os_mem_copy(void) {panic("[!!!] os_mem_copy: not implemented\n"); return -1;}
//int os_mem_set(void) {panic("[!!!] os_mem_set: not implemented\n"); return -1;}
//int os_memcpy_from_user(void) {panic("[!!!] os_memcpy_from_user: not implemented\n"); return -1;}
//int os_memcpy_to_user(void) {panic("[!!!] os_memcpy_to_user: not implemented\n"); return -1;}
int os_numa_memblock_size(void) {panic("[!!!] os_numa_memblock_size: not implemented\n"); return -1;}
//int os_nv_cap_close_fd(void) {panic("[!!!] os_nv_cap_close_fd: not implemented\n"); return -1;}
//int os_nv_cap_create_dir_entry(void) {panic("[!!!] os_nv_cap_create_dir_entry: not implemented\n"); return -1;}
//int os_nv_cap_create_file_entry(void) {panic("[!!!] os_nv_cap_create_file_entry: not implemented\n"); return -1;}
//int os_nv_cap_destroy_entry(void) {panic("[!!!] os_nv_cap_destroy_entry: not implemented\n"); return -1;}
//int os_nv_cap_validate_and_dup_fd(void) {panic("[!!!] os_nv_cap_validate_and_dup_fd: not implemented\n"); return -1;}
int os_open_temporary_file(void) {panic("[!!!] os_open_temporary_file: not implemented\n"); return -1;}
//int os_pat_supported(void) {panic("[!!!] os_pat_supported: not implemented\n"); return -1;}
//int os_pci_init_handle(void) {panic("[!!!] os_pci_init_handle: not implemented\n"); return -1;}
//int os_pci_read_byte(void) {panic("[!!!] os_pci_read_byte: not implemented\n"); return -1;}
//int os_pci_read_dword(void) {panic("[!!!] os_pci_read_dword: not implemented\n"); return -1;}
//int os_pci_read_word(void) {panic("[!!!] os_pci_read_word: not implemented\n"); return -1;}
//int os_pci_remove(void) {panic("[!!!] os_pci_remove: not implemented\n"); return -1;}
int os_pci_remove_supported(void) {panic("[!!!] os_pci_remove_supported: not implemented\n"); return -1;}
//int os_pci_write_byte(void) {panic("[!!!] os_pci_write_byte: not implemented\n"); return -1;}
//int os_pci_write_dword(void) {panic("[!!!] os_pci_write_dword: not implemented\n"); return -1;}
//int os_pci_write_word(void) {panic("[!!!] os_pci_write_word: not implemented\n"); return -1;}
int os_put_page(void) {panic("[!!!] os_put_page: not implemented\n"); return -1;}
int os_queue_work_item(void) {panic("[!!!] os_queue_work_item: not implemented\n"); return -1;}
int os_read_file(void) {panic("[!!!] os_read_file: not implemented\n"); return -1;}
//int os_registry_init(void) {panic("[!!!] os_registry_init: not implemented\n"); return -1;}
//int os_release_mutex(void) {panic("[!!!] os_release_mutex: not implemented\n"); return -1;}
//int os_release_semaphore(void) {panic("[!!!] os_release_semaphore: not implemented\n"); return -1;}
//int os_release_spinlock(void) {panic("[!!!] os_release_spinlock: not implemented\n"); return -1;}
//int os_schedule(void) {panic("[!!!] os_schedule: not implemented\n"); return -1;}
//int os_semaphore_may_sleep(void) {panic("[!!!] os_semaphore_may_sleep: not implemented\n"); return -1;}
//int os_snprintf(void) {panic("[!!!] os_snprintf: not implemented\n"); return -1;}
int os_string_compare(void) {panic("[!!!] os_string_compare: not implemented\n"); return -1;}
int os_string_copy(void) {panic("[!!!] os_string_copy: not implemented\n"); return -1;}
int os_string_length(void) {panic("[!!!] os_string_length: not implemented\n"); return -1;}
int os_strtoul(void) {panic("[!!!] os_strtoul: not implemented\n"); return -1;}
int os_unlock_user_pages(void) {panic("[!!!] os_unlock_user_pages: not implemented\n"); return -1;}
//int os_unmap_kernel_space(void) {panic("[!!!] os_unmap_kernel_space: not implemented\n"); return -1;}
//int os_unmap_user_space(void) {panic("[!!!] os_unmap_user_space: not implemented\n"); return -1;}
//int os_wait_interruptible(void) {panic("[!!!] os_wait_interruptible: not implemented\n"); return -1;}
//int os_wait_uninterruptible(void) {panic("[!!!] os_wait_uninterruptible: not implemented\n"); return -1;}
//int os_wake_up(void) {panic("[!!!] os_wake_up: not implemented\n"); return -1;}
int os_write_file(void) {panic("[!!!] os_write_file: not implemented\n"); return -1;}
//int out_string(void) {panic("[!!!] out_string: not implemented\n"); return -1;}

int libspdm_aead_aes_gcm_decrypt(void) {panic("[!!!] libspdm_aead_aes_gcm_decrypt: not implemented\n"); return -1;}
int libspdm_aead_aes_gcm_decrypt_prealloc(void) {panic("[!!!] libspdm_aead_aes_gcm_decrypt_prealloc: not implemented\n"); return -1;}
int libspdm_aead_aes_gcm_encrypt(void) {panic("[!!!] libspdm_aead_aes_gcm_encrypt: not implemented\n"); return -1;}
int libspdm_aead_aes_gcm_encrypt_prealloc(void) {panic("[!!!] libspdm_aead_aes_gcm_encrypt_prealloc: not implemented\n"); return -1;}
int libspdm_aead_free(void) {panic("[!!!] libspdm_aead_free: not implemented\n"); return -1;}
int libspdm_aead_gcm_prealloc(void) {panic("[!!!] libspdm_aead_gcm_prealloc: not implemented\n"); return -1;}
int libspdm_asn1_get_tag(void) {panic("[!!!] libspdm_asn1_get_tag: not implemented\n"); return -1;}
int libspdm_ec_compute_key(void) {panic("[!!!] libspdm_ec_compute_key: not implemented\n"); return -1;}
int libspdm_ec_free(void) {panic("[!!!] libspdm_ec_free: not implemented\n"); return -1;}
int libspdm_ec_generate_key(void) {panic("[!!!] libspdm_ec_generate_key: not implemented\n"); return -1;}
int libspdm_ec_get_public_key_from_x509(void) {panic("[!!!] libspdm_ec_get_public_key_from_x509: not implemented\n"); return -1;}
int libspdm_ec_new_by_nid(void) {panic("[!!!] libspdm_ec_new_by_nid: not implemented\n"); return -1;}
int libspdm_ecdsa_verify(void) {panic("[!!!] libspdm_ecdsa_verify: not implemented\n"); return -1;}
int libspdm_hkdf_sha256_expand(void) {panic("[!!!] libspdm_hkdf_sha256_expand: not implemented\n"); return -1;}
int libspdm_hkdf_sha256_extract(void) {panic("[!!!] libspdm_hkdf_sha256_extract: not implemented\n"); return -1;}
int libspdm_hkdf_sha384_expand(void) {panic("[!!!] libspdm_hkdf_sha384_expand: not implemented\n"); return -1;}
int libspdm_hkdf_sha384_extract(void) {panic("[!!!] libspdm_hkdf_sha384_extract: not implemented\n"); return -1;}
int libspdm_hmac_sha256_all(void) {panic("[!!!] libspdm_hmac_sha256_all: not implemented\n"); return -1;}
int libspdm_hmac_sha256_final(void) {panic("[!!!] libspdm_hmac_sha256_final: not implemented\n"); return -1;}
int libspdm_hmac_sha256_free(void) {panic("[!!!] libspdm_hmac_sha256_free: not implemented\n"); return -1;}
int libspdm_hmac_sha256_new(void) {panic("[!!!] libspdm_hmac_sha256_new: not implemented\n"); return -1;}
int libspdm_hmac_sha256_set_key(void) {panic("[!!!] libspdm_hmac_sha256_set_key: not implemented\n"); return -1;}
int libspdm_hmac_sha256_update(void) {panic("[!!!] libspdm_hmac_sha256_update: not implemented\n"); return -1;}
int libspdm_hmac_sha384_all(void) {panic("[!!!] libspdm_hmac_sha384_all: not implemented\n"); return -1;}
int libspdm_random_bytes(void) {panic("[!!!] libspdm_random_bytes: not implemented\n"); return -1;}
int libspdm_sha256_duplicate(void) {panic("[!!!] libspdm_sha256_duplicate: not implemented\n"); return -1;}
int libspdm_sha256_final(void) {panic("[!!!] libspdm_sha256_final: not implemented\n"); return -1;}
int libspdm_sha256_free(void) {panic("[!!!] libspdm_sha256_free: not implemented\n"); return -1;}
int libspdm_sha256_hash_all(void) {panic("[!!!] libspdm_sha256_hash_all: not implemented\n"); return -1;}
int libspdm_sha256_init(void) {panic("[!!!] libspdm_sha256_init: not implemented\n"); return -1;}
int libspdm_sha256_new(void) {panic("[!!!] libspdm_sha256_new: not implemented\n"); return -1;}
int libspdm_sha256_update(void) {panic("[!!!] libspdm_sha256_update: not implemented\n"); return -1;}
int libspdm_sha384_duplicate(void) {panic("[!!!] libspdm_sha384_duplicate: not implemented\n"); return -1;}
int libspdm_sha384_final(void) {panic("[!!!] libspdm_sha384_final: not implemented\n"); return -1;}
int libspdm_sha384_free(void) {panic("[!!!] libspdm_sha384_free: not implemented\n"); return -1;}
int libspdm_sha384_hash_all(void) {panic("[!!!] libspdm_sha384_hash_all: not implemented\n"); return -1;}
int libspdm_sha384_init(void) {panic("[!!!] libspdm_sha384_init: not implemented\n"); return -1;}
int libspdm_sha384_new(void) {panic("[!!!] libspdm_sha384_new: not implemented\n"); return -1;}
int libspdm_sha384_update(void) {panic("[!!!] libspdm_sha384_update: not implemented\n"); return -1;}
int libspdm_x509_compare_date_time(void) {panic("[!!!] libspdm_x509_compare_date_time: not implemented\n"); return -1;}
int libspdm_x509_get_cert_from_cert_chain(void) {panic("[!!!] libspdm_x509_get_cert_from_cert_chain: not implemented\n"); return -1;}
int libspdm_x509_get_extended_basic_constraints(void) {panic("[!!!] libspdm_x509_get_extended_basic_constraints: not implemented\n"); return -1;}
int libspdm_x509_get_extended_key_usage(void) {panic("[!!!] libspdm_x509_get_extended_key_usage: not implemented\n"); return -1;}
int libspdm_x509_get_extension_data(void) {panic("[!!!] libspdm_x509_get_extension_data: not implemented\n"); return -1;}
int libspdm_x509_get_issuer_name(void) {panic("[!!!] libspdm_x509_get_issuer_name: not implemented\n"); return -1;}
int libspdm_x509_get_key_usage(void) {panic("[!!!] libspdm_x509_get_key_usage: not implemented\n"); return -1;}
int libspdm_x509_get_serial_number(void) {panic("[!!!] libspdm_x509_get_serial_number: not implemented\n"); return -1;}
int libspdm_x509_get_subject_name(void) {panic("[!!!] libspdm_x509_get_subject_name: not implemented\n"); return -1;}
int libspdm_x509_get_validity(void) {panic("[!!!] libspdm_x509_get_validity: not implemented\n"); return -1;}
int libspdm_x509_get_version(void) {panic("[!!!] libspdm_x509_get_version: not implemented\n"); return -1;}
int libspdm_x509_set_date_time(void) {panic("[!!!] libspdm_x509_set_date_time: not implemented\n"); return -1;}
int libspdm_x509_verify_cert(void) {panic("[!!!] libspdm_x509_verify_cert: not implemented\n"); return -1;}
int libspdm_x509_verify_cert_chain(void) {panic("[!!!] libspdm_x509_verify_cert_chain: not implemented\n"); return -1;}
int libspdm_ecdsa_sign(void) {panic("[!!!] libspdm_ecdsa_sign: not implemented\n"); return -1;}
int libspdm_hmac_sha384_new(void) {panic("[!!!] libspdm_hmac_sha384_new: not implemented\n"); return -1;}
int libspdm_hmac_sha384_free(void) {panic("[!!!] libspdm_hmac_sha384_free: not implemented\n"); return -1;}
int libspdm_hmac_sha384_set_key(void) {panic("[!!!] libspdm_hmac_sha384_set_key: not implemented\n"); return -1;}
int libspdm_hmac_sha256_duplicate(void) {panic("[!!!] libspdm_hmac_sha256_duplicate: not implemented\n"); return -1;}
int libspdm_hmac_sha384_duplicate(void) {panic("[!!!] libspdm_hmac_sha384_duplicate: not implemented\n"); return -1;}
int libspdm_hmac_sha384_update(void) {panic("[!!!] libspdm_hmac_sha384_update: not implemented\n"); return -1;}
int libspdm_hmac_sha384_final(void) {panic("[!!!] libspdm_hmac_sha384_final: not implemented\n"); return -1;}
//int nv_acpi_dsm_method(void) {panic("[!!!] nv_acpi_dsm_method: not implemented\n"); return -1;}
int nv_acquire_mmap_lock(void) {panic("[!!!] nv_acquire_mmap_lock: not implemented\n"); return -1;}
int nv_allow_runtime_suspend(void) {panic("[!!!] nv_allow_runtime_suspend: not implemented\n"); return -1;}
//int nv_audio_dynamic_power(void) {panic("[!!!] nv_audio_dynamic_power: not implemented\n"); return -1;}
int nv_cancel_nano_timer(void) {panic("[!!!] nv_cancel_nano_timer: not implemented\n"); return -1;}
int nv_create_nano_timer(void) {panic("[!!!] nv_create_nano_timer: not implemented\n"); return -1;}
int nv_destroy_nano_timer(void) {panic("[!!!] nv_destroy_nano_timer: not implemented\n"); return -1;}
int nv_disallow_runtime_suspend(void) {panic("[!!!] nv_disallow_runtime_suspend: not implemented\n"); return -1;}
int nv_dynamic_power_available(void) {panic("[!!!] nv_dynamic_power_available: not implemented\n"); return -1;}
int nv_get_all_mappings_revoked_locked(void) {panic("[!!!] nv_get_all_mappings_revoked_locked: not implemented\n"); return -1;}
int nv_get_egm_info(void) {panic("[!!!] nv_get_egm_info: not implemented\n"); return -1;}
int nv_get_updated_emu_seg(void) {panic("[!!!] nv_get_updated_emu_seg: not implemented\n"); return -1;}
int nv_idle_holdoff(void) {panic("[!!!] nv_idle_holdoff: not implemented\n"); return -1;}
int nv_indicate_idle(void) {panic("[!!!] nv_indicate_idle: not implemented\n"); return -1;}
int nv_indicate_not_idle(void) {panic("[!!!] nv_indicate_not_idle: not implemented\n"); return -1;}
int nv_match_gpu_os_info(void) {panic("[!!!] nv_match_gpu_os_info: not implemented\n"); return -1;}
int nv_platform_supports_s0ix(void) {panic("[!!!] nv_platform_supports_s0ix: not implemented\n"); return -1;}
int nv_release_mmap_lock(void) {panic("[!!!] nv_release_mmap_lock: not implemented\n"); return -1;}
int nv_revoke_gpu_mappings(void) {panic("[!!!] nv_revoke_gpu_mappings: not implemented\n"); return -1;}
int nv_s2idle_pm_configured(void) {panic("[!!!] nv_s2idle_pm_configured: not implemented\n"); return -1;}
//int nv_set_primary_vga_status(void) {panic("[!!!] nv_set_primary_vga_status: not implemented\n"); return -1;}
int nv_set_safe_to_mmap_locked(void) {panic("[!!!] nv_set_safe_to_mmap_locked: not implemented\n"); return -1;}
int nv_start_nano_timer(void) {panic("[!!!] nv_start_nano_timer: not implemented\n"); return -1;}
int nvlink_get_platform_time(void) {panic("[!!!] nvlink_get_platform_time: not implemented\n"); return -1;}
int nvswitch_os_get_os_version(void) {panic("[!!!] nvswitch_os_get_os_version: not implemented\n"); return -1;}
int nvswitch_os_get_platform_time_epoch(void) {panic("[!!!] nvswitch_os_get_platform_time_epoch: not implemented\n"); return -1;}
//int os_acquire_rwlock_read(void) {panic("[!!!] os_acquire_rwlock_read: not implemented\n"); return -1;}
//int os_acquire_rwlock_write(void) {panic("[!!!] os_acquire_rwlock_write: not implemented\n"); return -1;}
//int os_alloc_rwlock(void) {panic("[!!!] os_alloc_rwlock: not implemented\n"); return -1;}
int os_call_vgpu_vfio(void) {panic("[!!!] os_call_vgpu_vfio: not implemented\n"); return -1;}
//int os_cond_acquire_rwlock_read(void) {panic("[!!!] os_cond_acquire_rwlock_read: not implemented\n"); return -1;}
//int os_cond_acquire_rwlock_write(void) {panic("[!!!] os_cond_acquire_rwlock_write: not implemented\n"); return -1;}
int os_enable_pci_req_atomics(void) {panic("[!!!] os_enable_pci_req_atomics: not implemented\n"); return -1;}
//int os_find_ns_pid(void) {panic("[!!!] os_find_ns_pid: not implemented\n"); return -1;}
//int os_free_rwlock(void) {panic("[!!!] os_free_rwlock: not implemented\n"); return -1;}
//int os_get_max_user_va(void) {panic("[!!!] os_get_max_user_va: not implemented\n"); return -1;}
int os_get_numa_node_memory_usage(void) {panic("[!!!] os_get_numa_node_memory_usage: not implemented\n"); return -1;}
//int os_get_pid_info(void) {panic("[!!!] os_get_pid_info: not implemented\n"); return -1;}
int os_inject_vgx_msi(void) {panic("[!!!] os_inject_vgx_msi: not implemented\n"); return -1;}
int os_io_read_dword(void) {panic("[!!!] os_io_read_dword: not implemented\n"); return -1;}
int os_io_write_dword(void) {panic("[!!!] os_io_write_dword: not implemented\n"); return -1;}
int os_numa_add_gpu_memory(void) {panic("[!!!] os_numa_add_gpu_memory: not implemented\n"); return -1;}
int os_numa_remove_gpu_memory(void) {panic("[!!!] os_numa_remove_gpu_memory: not implemented\n"); return -1;}
int os_offline_page_at_address(void) {panic("[!!!] os_offline_page_at_address: not implemented\n"); return -1;}
//int os_put_pid_info(void) {panic("[!!!] os_put_pid_info: not implemented\n"); return -1;}
//int os_release_rwlock_read(void) {panic("[!!!] os_release_rwlock_read: not implemented\n"); return -1;}
//int os_release_rwlock_write(void) {panic("[!!!] os_release_rwlock_write: not implemented\n"); return -1;}
int libspdm_check_crypto_backend(void) {panic("[!!!] libspdm_check_crypto_backend: not implemented\n"); return -1;}
int libspdm_rsa_free(void) {panic("[!!!] libspdm_rsa_free: not implemented\n"); return -1;}
int libspdm_rsa_get_public_key_from_x509(void) {panic("[!!!] libspdm_rsa_get_public_key_from_x509: not implemented\n"); return -1;}
int libspdm_rsa_new(void) {panic("[!!!] libspdm_rsa_new: not implemented\n"); return -1;}
int libspdm_rsa_pss_sign(void) {panic("[!!!] libspdm_rsa_pss_sign: not implemented\n"); return -1;}
int libspdm_rsa_pss_verify(void) {panic("[!!!] libspdm_rsa_pss_verify: not implemented\n"); return -1;}
int libspdm_rsa_set_key(void) {panic("[!!!] libspdm_rsa_set_key: not implemented\n"); return -1;}
//int nv_get_disp_smmu_stream_ids(void) {panic("[!!!] nv_get_disp_smmu_stream_ids: not implemented\n"); return -1;}
//int nv_get_screen_info(void) {panic("[!!!] nv_get_screen_info: not implemented\n"); return -1;}
int nvswitch_os_get_pid(void) {panic("[!!!] nvswitch_os_get_pid: not implemented\n"); return -1;}
//int os_get_grid_csp_support(void) {panic("[!!!] os_get_grid_csp_support: not implemented\n"); return -1;}
int os_imex_channel_count(void) {panic("[!!!] os_imex_channel_count: not implemented\n"); return -1;}
int os_imex_channel_get(void) {panic("[!!!] os_imex_channel_get: not implemented\n"); return -1;}
int os_imex_channel_is_supported(void) {panic("[!!!] os_imex_channel_is_supported: not implemented\n"); return -1;}
//int os_is_grid_supported(void) {panic("[!!!] os_is_grid_supported: not implemented\n"); return -1;}
int nv_schedule_uvm_drain_p2p(void) {panic("[!!!] nv_schedule_uvm_drain_p2p: not implemented\n"); return -1;}
int nv_schedule_uvm_resume_p2p(void) {panic("[!!!] nv_schedule_uvm_resume_p2p: not implemented\n"); return -1;}
