/* Generated by tools/wifi/generate-icon.py. MIT License. */
#ifndef WIFI_ICON_PATHS_H
#define WIFI_ICON_PATHS_H

#include <Point.h>

struct WiFiIconPath {
	int32 count;
	BPoint points[19];
};

static const WiFiIconPath kWiFiIconPaths[] = {
	{ 13, {
		BPoint(36.5000f, 51.0000f),
		BPoint(36.5000f, 53.4853f),
		BPoint(34.4853f, 55.5000f),
		BPoint(32.0000f, 55.5000f),
		BPoint(29.5147f, 55.5000f),
		BPoint(27.5000f, 53.4853f),
		BPoint(27.5000f, 51.0000f),
		BPoint(27.5000f, 48.5147f),
		BPoint(29.5147f, 46.5000f),
		BPoint(32.0000f, 46.5000f),
		BPoint(34.4853f, 46.5000f),
		BPoint(36.5000f, 48.5147f),
		BPoint(36.5000f, 51.0000f),
	} },
	{ 13, {
		BPoint(21.0880f, 39.2983f),
		BPoint(27.2339f, 33.5672f),
		BPoint(36.7661f, 33.5672f),
		BPoint(42.9120f, 39.2983f),
		BPoint(42.9120f, 39.2983f),
		BPoint(38.4790f, 44.0521f),
		BPoint(38.4790f, 44.0521f),
		BPoint(34.8299f, 40.6493f),
		BPoint(29.1701f, 40.6493f),
		BPoint(25.5210f, 44.0521f),
		BPoint(25.5210f, 44.0521f),
		BPoint(21.0880f, 39.2983f),
		BPoint(21.0880f, 39.2983f),
	} },
	{ 13, {
		BPoint(12.9040f, 30.5221f),
		BPoint(23.6593f, 20.4926f),
		BPoint(40.3407f, 20.4926f),
		BPoint(51.0960f, 30.5221f),
		BPoint(51.0960f, 30.5221f),
		BPoint(46.6630f, 35.2759f),
		BPoint(46.6630f, 35.2759f),
		BPoint(38.4044f, 27.5747f),
		BPoint(25.5956f, 27.5747f),
		BPoint(17.3370f, 35.2759f),
		BPoint(17.3370f, 35.2759f),
		BPoint(12.9040f, 30.5221f),
		BPoint(12.9040f, 30.5221f),
	} },
	{ 13, {
		BPoint(4.7201f, 21.7459f),
		BPoint(20.0848f, 7.4180f),
		BPoint(43.9152f, 7.4180f),
		BPoint(59.2799f, 21.7459f),
		BPoint(59.2799f, 21.7459f),
		BPoint(54.8469f, 26.4997f),
		BPoint(54.8469f, 26.4997f),
		BPoint(41.9790f, 14.5001f),
		BPoint(22.0210f, 14.5001f),
		BPoint(9.1531f, 26.4997f),
		BPoint(9.1531f, 26.4997f),
		BPoint(4.7201f, 21.7459f),
		BPoint(4.7201f, 21.7459f),
	} },
};

#endif // WIFI_ICON_PATHS_H
