#!/bin/sh
case "$1" in
    --native|--software) ;;
    *) exit 2 ;;
esac
export LIBRARY_PATH=/boot/home/mesa-trial/lib:/boot/system/lib:/boot/system/non-packaged/lib:/boot/home/config/lib:/boot/home/config/non-packaged/lib
export __EGL_VENDOR_LIBRARY_FILENAMES=/boot/home/mesa-trial/vendor.json
/boot/home/mesa-trial/rock5_haiku_loss_probe "$1" || exit $?
/boot/home/mesa-trial/run-pipeline "$1" || exit $?
echo ROCK5_LOSS_GRAPHICS_PASS
