#!/bin/sh
set -eu
[ "$#" -eq 1 ]
case "$1" in --native|--software) ;; *) exit 2 ;; esac
export LIBRARY_PATH=/boot/home/mesa-trial/lib:/boot/system/lib:/boot/system/non-packaged/lib:/boot/home/config/lib:/boot/home/config/non-packaged/lib
export __EGL_VENDOR_LIBRARY_FILENAMES=/boot/home/mesa-trial/vendor.json
# This candidate explicitly opts into the bounded non-solid geometry path.
if [ "$1" = --native ]; then export HAIKU_PAN_SW_POLYGON=1; fi
exec /boot/home/mesa-trial/rock5_polygon_probe "$1"
