#!/usr/bin/env python3
"""Generate the Wi-Fi application icon and matching Deskbar geometry.

Run from any directory. Uses the fork's native HVIF writer; no raster assets.
"""

import math
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tools/airos-branding'))
import airos_art as art
import hvif


def line(start, end):
    return [start, start, end, end]


def band(radius):
    start, end = map(math.radians, (227, 313))
    outer = art.arc((32, 51), radius, start, end)
    inner = art.arc((32, 51), radius - 6.5, end, start)
    return outer + [line(outer[-1][3], inner[0][0])] + inner + [
        line(inner[-1][3], outer[0][0])]


def generate():
    # Inner to outer: the dot and three arcs represent four signal levels.
    contours = [art.circle((32, 51), 4.5)] + [band(r) for r in (16, 28, 40)]
    icon = hvif.Icon()
    shadow = icon.solid((0, 0, 0), 35)
    outline = icon.solid((22, 48, 65))
    paths = [icon.path(contour) for contour in contours]
    icon.shape(shadow, paths, matrix=[1, 0, 0, 1, 1, 1.5], stroke=3)
    for path, contour in zip(paths, contours):
        top = min(point[1] for segment in contour for point in segment)
        bottom = max(point[1] for segment in contour for point in segment)
        face = icon.gradient(hvif.GRADIENT_LINEAR,
            hvif.linear_matrix((22, top), (38, bottom)),
            [(0, (190, 236, 255)), (0.30, (103, 190, 230)),
             (0.70, (49, 134, 184)), (1, (32, 93, 144))])
        icon.shape(outline, [path], stroke=2)
        icon.shape(face, [path])

    for relative in ('src/preferences/wifi/WiFi.rdef',
                     'src/apps/wifistatus/WiFiStatus.rdef'):
        path = ROOT / relative
        text = path.read_text().split('\n// Generated by tools/wifi/')[0].rstrip()
        path.write_text(text + '\n\n// Generated by tools/wifi/generate-icon.py.\n'
            + icon.rdef('vector_icon array'))

    header = ['/* Generated by tools/wifi/generate-icon.py. MIT License. */',
        '#ifndef WIFI_ICON_PATHS_H', '#define WIFI_ICON_PATHS_H', '',
        '#include <Point.h>', '',
        'struct WiFiIconPath {', '\tint32 count;', '\tBPoint points[19];', '};', '',
        'static const WiFiIconPath kWiFiIconPaths[] = {']
    for contour in contours:
        points = [contour[0][0]] + [p for segment in contour for p in segment[1:]]
        header.append('\t{ %d, {' % len(points))
        header.extend('\t\tBPoint(%.4ff, %.4ff),' % p for p in points)
        header.append('\t} },')
    header.extend(['};', '', '#endif // WIFI_ICON_PATHS_H', ''])
    (ROOT / 'src/preferences/wifi/WiFiIconPaths.h').write_text('\n'.join(header))
    return icon


if __name__ == '__main__':
    generate()
